# Generated by Django 2.1.4 on 2018-12-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0002_auto_20181224_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumini',
            fields=[
                ('alumini_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('number', models.IntegerField()),
                ('pass_out_year', models.CharField(max_length=10)),
                ('cgpa', models.IntegerField()),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Batch')),
            ],
        ),
    ]
