# Generated by Django 2.1.4 on 2018-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='sem_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
