# Generated by Django 2.1.4 on 2019-02-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20190214_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='noticeFile',
            field=models.FileField(upload_to=''),
        ),
    ]
