# Generated by Django 2.1.4 on 2019-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20190215_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slideId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
