# Generated by Django 2.1.4 on 2019-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slideCaption',
            field=models.CharField(default='Picture', max_length=30),
        ),
        migrations.AddField(
            model_name='slide',
            name='slidePic',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
