# Generated by Django 2.1.4 on 2019-03-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20190228_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slidePic',
            field=models.FileField(upload_to=''),
        ),
    ]
