# Generated by Django 2.1.4 on 2019-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20190302_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
