# Generated by Django 2.1.4 on 2019-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_content', models.CharField(max_length=1000)),
                ('event_header', models.CharField(max_length=50)),
                ('event_img', models.FileField(upload_to='')),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
